export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const CONTACT_UPDATED = 'CONTACT_UPDATED';
export const CONTACT_REMOVED = 'CONTACT_REMOVED';
export const CONTACT_CREATED = 'CONTACT_CREATED';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';