export const RECEIVE_NOTIFICATION_FROM_SERVER = 'RECEIVE_NOTIFICATION_FROM_SERVER';
export const NOTIFICATION_FROM_SERVER_SEEN = 'NOTIFICATION_FROM_SERVER_SEEN';
export const ALERT_JUMPED = 'ALERT_JUMPED';
